#include <iomanip>
#include <iostream>
#include <random>

#include "banker.h"

using std::cin;
using std::cout;
using std::endl;
using std::setw;
using std::vector;


enum material {
    glass,
    metal,
    wood
};

struct Bottle {
    float volume;
    material mat;
    float diameter;
};

void t1() {
    Banker rothschild;
    float test = 10.0;
    float double_test;
    rothschild.setAge(72);
    cout << rothschild.getAge() << endl;
    cout << test/3 << endl;
    float aThird = test/3;
    cout << aThird << endl;
    cout << aThird*3 << endl;
}


void t2() {
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> distrib(0, 10000);

    for (int n=0; n<2048; ++n) {
        //Use `distrib` to transform the random unsigned int generated by gen into an int
        cout << setw(10) << distrib(gen) << endl;
    }
}

template<typename T>
void print(T* val) {
    cout << val << endl;
}

void t3() {
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> distrib(0, 10000);

    int numbers[2048];
    for (int i=0; i<2048; i++) {
        //Use `distrib` to transform the random unsigned int generated by gen into an int
        numbers[i] = distrib(gen);
    }

    for (int i=0; i<2048; i++) {
        cout << setw(10) << numbers[i] << endl;
    }
}


void t4() {
    int blaa[1] = { 1 };
    cout << sizeof(blaa) / sizeof(blaa[0]) << endl;
}

void t5() {
    vector<int> v;
    v.push_back(123);
    cout << v[0] << endl;
}

void t6() {
    int size;
    cout << "Size -> ";
    cin >> size;

    int *integers = new int[size];

    for(int i = 0; i < size; i++) {
        cout << "integers[" << i << "] ";
        cin >> integers[i];
    }

    for(int i = 0; i < size; i++) {
        cout << integers[i];
    }

    cout << endl;

    delete[]integers;
    integers = NULL;
}
int main() {
    t6();
}